### ISSUE TITLE
Updates on support programmes

### ISSUE THREAD

**Issue by MeIngBest** [neurolabusc/AppleSiliconForNeuroimaging#5]
Thanks a lot for that great post!

Are there any updates if FSL and AFNI can be now easily installed and used on the M! chip? I think FSL works fin now.
What about nibabel, FMRIPREP, ciftify and freesurfer?

Best,

**Comment by neurolabusc** [comment]
@hanayik may want to comment about FSL. When I tested it, it ran [fine via Rosetta translation](https://github.com/neurolabusc/AppleSiliconForNeuroimaging#software-evaluated). Acinonyx [reports](https://neurostars.org/t/apple-silicon-m1-compatibility-freesurfer-yes-everything-else-no/17686) that FreeSurfer works fine via Rosetta translation. Since fMRIPrep is set of Python scripts that use [FSL, ANTs, FreeSurfer and AFNI.](https://fmriprep.org/en/stable/), I expect it works fine. 

However, as I note on the web page, NumPy performance on the M1 is mixed: some functions are faster natively, while others that use SIMD run faster as Rosetta translations. This will remain the case until Numpy [supports ARM64 SIMD intrinsics](https://github.com/numpy/numpy/issues/17989). Perhaps @Developer-Ecosystem-Engineering want to comment. Given Apple is one of the worlds most valuable companies, one might speculate that their failure to devote resources to core tools like Numpy may be intentional (e.g. future CPUs may support SVE, so there is little rationale to support Neon).

**Comment by neurolabusc** [comment]
@afni-dglen can comment on AFNI. My understanding is that AFNI can be [built natively for the M1](https://github.com/afni/afni/pull/233) but that XQuartz has some limitations for the graphical tools.

**Comment by afni-dglen** [comment]
AFNI does indeed build without any difficulty on ARM M1, but we are still trying to get code signing to work properly for distribution. The code signing has complications from XQuartz's own code signing and AFNI's library dependencies from the XQuartz package. XQuartz does pose some other challenges, but it seems to be working well for the afni and suma GUIs. XQuartz seems to work better with 60Hz refresh rate and can become tediously slow if other refresh rates are used.
For now, we recommend either building from source on ARM systems or using the Intel version in Rosetta emulation mode.

**Comment by neurolabusc** [comment]
Updated page. Thanks!
